### ISSUE TITLE
Smartthings Ring 2FA

### ISSUE THREAD

**Issue by RagDaz** [jsetton/smartthings-ring#16]
Hi, I have a Ring Wireless Stick Up cam and have installed files on Smartthings IDE from your GIT, everything looks ok except when input my username and password it fails and I think this is due to no 2FA box appearing so I can input the code.  Any idea what I have done wrong?

Rory

**Comment by jsetton** [comment]
If it fails after you entered your username and password, then there is problem with your credentials. The 2FA code will show on the subsequent screen if your credentials are valid.

**Comment by RagDaz** [comment]
Logon details are correct, just tried via the web and had to input the code, just comes up with Login failed.  Do I need to enable OAuth?

**Comment by jsetton** [comment]
As far as I know, unless something changed recently, there is nothing you should be configuring on the Ring side since 2FA is required by default. Check your Smartthings IDE logs to see the http error code returned on your initial connection. It should be 412 Precondition Failed which triggers the 2FA code.

**Comment by RagDaz** [comment]
This is what I see in the logs
ec8037f6-32a0-49db-80ab-2062ecf56f38  11:43:22 am: error HTTP POST Exception: groovyx.net.http.HttpResponseException: Not Acceptable
ec8037f6-32a0-49db-80ab-2062ecf56f38  11:43:21 am: debug Getting oauth token...

**Comment by jsetton** [comment]
You most likely going through a VPN.

https://community.ring.com/t/406-not-acceptable/7521

**Comment by RagDaz** [comment]
Just checked and no vpn running, can logon and get verification code via the Mobile Chrome app

**Comment by RagDaz** [comment]
Tried it via my iPad Smartthings app and same issue occurs, Samsung phone via 4g and iPad via wifi

**Comment by jsetton** [comment]
Actually the connection should be coming from the Smartthings network. It might related to the [user agent](https://github.com/jsetton/smartthings-ring/blob/master/smartapps/jsetton/ring-device-manager.src/ring-device-manager.groovy#L398). It's probably getting old.

Other than that I don't know. I will have to debug the connection when I get a chance. I would recommend using the official Ring integration until then.

**Comment by RagDaz** [comment]
Thanks, I use the Smartthing and Ring integration but only works for the Ring Doorbell, not the Ring Wireless Cam - think it might be a region issue as I live in New Zealand, says compatible but not certified but if I select it, it does not show in the device list.  Will have to leave it until ST updates to allow it to be added - thanks for your prompt replies :)

**Comment by jsetton** [comment]
No worries. The 406 http error could also be due to your location.
