### ISSUE TITLE
Two Factor Blank Page

### ISSUE THREAD

**Issue by jdugan4859** [jsetton/smartthings-ring#5]
There doesn't seem to be a way to add the verification page. Once I put in my UN/P it just takes me to a blank page.

**Comment by jsetton** [comment]
Could you attach a screenshot? First, you need to enter your username and password. If you have two factor enabled on your Ring account, you should receive a text message and the setup page will give the ability to enter the code that was sent. Keep in mind that Ring has implemented temporary ban when making too many unsuccessful login requests in a short period.

**Comment by jdugan4859** [comment]
I am running of the most recent version on Github.

I go to the main setup page and enter my credentials.



I press next, and am taken to the next page, and then get the text message from Ring, but I’m never given a place to enter the code.




If I press done, it just gives me an error.

**Comment by jsetton** [comment]
Ring changed some of the information sent after the initial login when 2fa is enabled. I will apply a patch to correct this.

**Comment by jsetton** [comment]
@jdugan4859 I have merged a fix for this one. Just use the latest version and you should be all set. Thanks for raising this one 👍
