### ISSUE TITLE
Sirens not shown in the new app

### ISSUE THREAD

**Issue by jdugan4859** [jsetton/smartthings-ring#8]
Looks like for some reason the device for the siren is not showing up in the new app.

**Comment by jsetton** [comment]
Which Ring device(s) do you have setup? Also, could you add a screenshot of what you are seeing in the new app?

**Comment by jdugan4859** [comment]
Sorry, I’ve been away for awhile. The one I’m having problems with is the Floodlight Cam. I am attaching a screenshot of my Floodlight Cam(Driveway) and my Spot Light Cam(Porch)
![77EE7775-F091-468B-996C-759188F345C1](https://user-images.githubusercontent.com/37936368/91668572-a24e4f80-eadb-11ea-813a-0e1212b6061b.png)
![6980A9A2-A4F8-43C5-A235-F002D5C354F6](https://user-images.githubusercontent.com/37936368/91668573-a24e4f80-eadb-11ea-9597-3e781927996a.png)

**Comment by jsetton** [comment]
This was fixed in #10.
