### ISSUE TITLE
Problem installing SmartApp on IOS

### ISSUE THREAD

**Issue by fnapoleone** [jsetton/smartthings-ring#9]
Hello,

I've tried to install the SmartApp using the Smarthings App on IOS, During the install, it looks like the initial Ring account password authentication works, but when it prompts me for the 2FA code that was sent to my phone (i.e. via SMS), I enter the code and click Next but nothing happens.

Thanks
-Fino

**Comment by jsetton** [comment]
This was fixed in #10
